"""A single, shared implementation of "run a transform" (TODO
`54d8c18`). See design-docs/transforms.md.

Follows the same shape as desk_services.file_watcher/desk_services
.popups (a plain class, a module-level lazily-constructed
get_service() singleton). Like popups, not Qt-agnostic: the JS/TS
execution path needs QObject/pyqtSignal to marshal a background
-thread result back onto the GUI thread, and run_blocking/
identity_blocking need QEventLoop.
"""

from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
import sys
import threading
from collections.abc import Callable
from pathlib import Path
from types import ModuleType

from PyQt6.QtCore import QEventLoop, QObject, QTimer, pyqtSignal

from desk.transforms import TransformInfo, discover_transforms_with_errors

NODE_TIMEOUT_SECONDS = 30.0
OnResult = Callable[[str | None, str | None], None]  # (output, error) -- exactly one is not None


class TransformError(Exception):
    pass


class _JsRelay(QObject):
    """Owns the pyqtSignal a background node-subprocess thread reports
    through -- same shape as widgets/git_status//git_diff's own
    relays. Carries the specific on_result callback to invoke (rather
    than a fixed slot per transform) since many different callers can
    each have their own in-flight JS/TS transform at once."""

    finished = pyqtSignal(object, object, object)  # on_result: OnResult, output: str | None, error: str | None


def _load_transform_module(transform_id: str, transform_path: Path, entry: str) -> ModuleType:
    """Mirrors desk.shell.python_widget._load_widget_module exactly --
    including the __pycache__-suppression trick -- for a Python
    transform's entry file."""
    module_path = transform_path / entry
    spec = importlib.util.spec_from_file_location(f"desk_transform_{transform_id}", module_path)
    if spec is None or spec.loader is None:
        raise TransformError(f"Cannot load transform module at {module_path}")
    module = importlib.util.module_from_spec(spec)
    previous_dont_write_bytecode = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        spec.loader.exec_module(module)
    finally:
        sys.dont_write_bytecode = previous_dont_write_bytecode
    return module


NODE_GLOBALS_DECLARATIONS_FILENAME = "_desk_transform_node_globals.d.ts"
# Minimal ambient declarations for the small subset of Node's global API
# a transform's stdin/stdout JSON protocol needs (see
# design-docs/transforms.md) -- lets a TypeScript transform compile
# without needing the real @types/node package as a dependency (this
# project avoids adding dependencies where a small bespoke alternative
# works -- see CLAUDE.md). Auto-written into each TypeScript transform's
# own directory before building, safe to regenerate/overwrite.
_NODE_GLOBALS_DECLARATIONS = """// Auto-generated by Desk (TODO 54d8c18) -- do not hand-edit, safe to
// overwrite. See design-docs/transforms.md.
declare const process: {
  stdin: {
    on(event: "data", listener: (chunk: Buffer) => void): void;
    on(event: "end", listener: () => void): void;
  };
  stdout: {
    write(data: string): void;
  };
};

declare class Buffer {
  toString(encoding?: string): string;
}
"""


def _ensure_node_globals_declarations(transform_dir: Path) -> None:
    declarations_path = transform_dir / NODE_GLOBALS_DECLARATIONS_FILENAME
    if not declarations_path.is_file() or declarations_path.read_text() != _NODE_GLOBALS_DECLARATIONS:
        declarations_path.write_text(_NODE_GLOBALS_DECLARATIONS)


def _resolve_js_entry(info: TransformInfo) -> Path:
    """Resolves the actual runnable .js file for a JavaScript/
    TypeScript transform -- building it first (tsc -p <dir>) if it's a
    TypeScript transform whose compiled output is missing or older
    than its source. Called from the background thread a JS/TS
    transform always runs on (see _run_js_transform) -- this build
    step is itself a blocking subprocess call, so it must never run on
    the GUI thread either."""
    if info.kind == "javascript":
        return info.path / info.entry

    tsconfig_path = info.path / "tsconfig.json"
    try:
        tsconfig = json.loads(tsconfig_path.read_text())
    except (OSError, json.JSONDecodeError) as e:
        raise TransformError(f"{info.id}: couldn't read tsconfig.json: {e}") from e
    out_dir = tsconfig.get("compilerOptions", {}).get("outDir")
    if not out_dir:
        raise TransformError(f"{info.id}: tsconfig.json must set compilerOptions.outDir")

    source_path = info.path / info.entry
    compiled_entry = info.path / out_dir / f"{Path(info.entry).stem}.js"
    needs_build = (
        not compiled_entry.is_file() or source_path.stat().st_mtime > compiled_entry.stat().st_mtime
    )
    if needs_build:
        _ensure_node_globals_declarations(info.path)
        result = subprocess.run(["tsc", "-p", str(info.path)], capture_output=True, text=True)
        if result.returncode != 0:
            raise TransformError(f"{info.id}: tsc failed:\n{result.stdout}\n{result.stderr}")
    if not compiled_entry.is_file():
        raise TransformError(f"{info.id}: tsc did not produce the expected {compiled_entry}")
    return compiled_entry


def _run_js_transform(
    info: TransformInfo, action: str, input_data: str, config: dict | None, on_result: OnResult, relay: _JsRelay
) -> None:
    """Runs entirely on a background thread -- module-level, not a
    method, and must not touch any Qt widget directly (only ever
    reports back via the relay's signal), same discipline as widgets/
    git_status//git_diff's own git-subprocess threads. Both the
    on-demand tsc build and the node invocation are blocking
    subprocess calls; per LEARNINGS.md, neither may ever run on the
    GUI thread."""
    try:
        entry_path = _resolve_js_entry(info)
    except TransformError as e:
        relay.finished.emit(on_result, None, str(e))
        return

    request = json.dumps({"action": action, "input": input_data, "config": config})
    try:
        result = subprocess.run(
            ["node", str(entry_path)],
            input=request,
            capture_output=True,
            text=True,
            timeout=NODE_TIMEOUT_SECONDS,
        )
    except (subprocess.SubprocessError, OSError) as e:
        relay.finished.emit(on_result, None, str(e))
        return

    try:
        response = json.loads(result.stdout)
    except json.JSONDecodeError:
        relay.finished.emit(
            on_result, None, f"transform produced non-JSON stdout: {result.stdout!r} (stderr: {result.stderr!r})"
        )
        return
    if "error" in response:
        relay.finished.emit(on_result, None, str(response["error"]))
        return
    relay.finished.emit(on_result, response.get("output"), None)


class TransformsService:
    """Construct one directly for isolated use (e.g. tests); the app
    itself uses the shared get_service() singleton."""

    def __init__(self) -> None:
        self._transforms: dict[str, TransformInfo] = {}
        self._python_modules: dict[str, ModuleType] = {}
        self._js_relay = _JsRelay()
        self._js_relay.finished.connect(lambda on_result, output, error: on_result(output, error))

    def discover(
        self, desk_temp_dir: Path | None, project_dir: Path | None
    ) -> tuple[dict[str, TransformInfo], dict[str, str]]:
        """Refreshes the set of transforms run()/identity() resolve a
        transform_id against, and returns (transforms, errors) for a
        caller (the Transform Manager widget) that wants to display
        the current picture directly."""
        self._transforms, errors = discover_transforms_with_errors(desk_temp_dir, project_dir)
        return self._transforms, errors

    def _require(self, transform_id: str) -> TransformInfo:
        info = self._transforms.get(transform_id)
        if info is None:
            raise TransformError(f"Unknown transform: {transform_id!r} (call discover() first)")
        return info

    def _run_python(self, info: TransformInfo, action: str, input_data: str, config: dict | None) -> str:
        module = self._python_modules.get(info.id)
        if module is None:
            module = _load_transform_module(info.id, info.path, info.entry)
            self._python_modules[info.id] = module
        func = getattr(module, action, None)
        if func is None:
            raise TransformError(f"{info.id}: no {action}() function defined")
        return func(input_data, config)

    def _invoke(self, transform_id: str, action: str, input_data: str, config: dict | None, on_result: OnResult) -> None:
        try:
            info = self._require(transform_id)
        except TransformError as e:
            on_result(None, str(e))
            return
        if info.kind == "python":
            # Synchronous, in-process, on whichever thread calls this --
            # required, not just simplest: a Qt-touching Python transform
            # (both Mermaid transforms build a QGraphicsScene) must run on
            # the GUI thread, since Qt's graphics classes aren't
            # thread-safe to construct off it.
            try:
                output = self._run_python(info, action, input_data, config)
            except Exception as e:  # noqa: BLE001 -- never propagate a transform's own bug into the caller
                on_result(None, str(e))
                return
            on_result(output, None)
            return
        thread = threading.Thread(
            target=_run_js_transform, args=(info, action, input_data, config, on_result, self._js_relay), daemon=True
        )
        thread.start()

    def run(self, transform_id: str, input_data: str, config: dict | None, on_result: OnResult) -> None:
        self._invoke(transform_id, "run", input_data, config, on_result)

    def identity(self, transform_id: str, input_data: str, config: dict | None, on_result: OnResult) -> None:
        self._invoke(transform_id, "identity", input_data, config, on_result)

    def _run_blocking(self, transform_id: str, action: str, input_data: str, config: dict | None) -> str:
        loop = QEventLoop()
        result_holder: dict[str, str | None] = {}

        def on_result(output: str | None, error: str | None) -> None:
            result_holder["output"] = output
            result_holder["error"] = error
            # A Python transform's on_result fires synchronously, inside
            # the _invoke() call below -- i.e. *before* loop.exec() has
            # even started. Calling loop.quit() directly here is a real
            # hang hazard: quit() only has an effect on a loop that's
            # already running, so a quit issued before exec() starts can
            # be silently dropped, leaving the exec() call below block
            # forever waiting for a quit that already happened.
            # QTimer.singleShot(0, ...) defers the actual quit() to the
            # loop's own next iteration, which is only reachable once
            # exec() is genuinely running -- safe for both the
            # synchronous (Python) and asynchronous (JS/TS, where the
            # loop is already running by the time this fires) cases.
            QTimer.singleShot(0, loop.quit)

        self._invoke(transform_id, action, input_data, config, on_result)
        loop.exec()
        if result_holder.get("error") is not None:
            raise TransformError(result_holder["error"])
        return result_holder["output"]

    def run_blocking(self, transform_id: str, input_data: str, config: dict | None = None) -> str:
        return self._run_blocking(transform_id, "run", input_data, config)

    def identity_blocking(self, transform_id: str, input_data: str, config: dict | None = None) -> str:
        return self._run_blocking(transform_id, "identity", input_data, config)

    def promote(self, transform_id: str, desk_temp_dir: Path, project_dir: Path) -> None:
        """Moves a .desk_temp/transforms/<id>/ directory to
        desk_transforms/<id>/ -- mirrors desk.shell.window
        ._relocate_promoted_widget_source's own shutil.move shape.
        Only ever a TypeScript/JavaScript transform in practice (a
        Python transform is never discoverable under .desk_temp in the
        first place)."""
        source = desk_temp_dir / transform_id
        if not source.is_dir():
            raise TransformError(f"{transform_id}: not found under {desk_temp_dir}")
        destination = project_dir / transform_id
        if destination.exists():
            raise TransformError(f"{transform_id}: {destination} already exists")
        project_dir.mkdir(parents=True, exist_ok=True)
        shutil.move(str(source), str(destination))


_service: TransformsService | None = None


def get_service() -> TransformsService:
    """The process-wide shared instance every widget/Bridge-API call
    uses. Lazily constructed (not at import time), same convention as
    desk_services.file_watcher/desk_services.popups."""
    global _service
    if _service is None:
        _service = TransformsService()
    return _service
