"""Generates real TypeScript (+ CSS, for a "split" layout) from a
parsed AppDefinition (schema.py) -- see README.md for the DSL format
and plans/app-structure-dsl.md (Desk repo) for the design this
implements.

The generated code has zero Desk-specific content in it (no Bridge API
calls, nothing) unless an escape-hatch handler's own hand-written code
adds some. Two output modes (TODO 1e032f3):

- `mode="module"` (default): real ES modules (`import`/`export`) --
  for a standalone build, where the project's own `tsc`/bundler
  already understands them.
- `mode="global"`: no `import`/`export` at all -- global `class`/
  `let`/`function`/`const` declarations, for
  `.desk_temp/build_widget.py`'s own `DefineWidget` packaging model,
  which concatenates *non-module* scripts (confirmed directly: a file
  using `export`/`import` always gets CommonJS-style `exports`/
  `require` boilerplate in its compiled output, regardless of the
  `module` compiler option -- there is no way to get plain
  global-script output from a file containing ES module syntax).
  Component/handler source files must also avoid module syntax when
  used with this mode -- see README.md.

See DslError for the one class of thing this module refuses to
generate (an unimplemented layout mode)."""

import json
import os

from schema import (
    AppDefinition,
    CallAction,
    ComponentEntry,
    DslError,
    SplitLayoutNode,
    StateMutationAction,
)

GENERATED_TS_FILENAME = "app-wiring.ts"
GENERATED_CSS_FILENAME = "app-layout.css"
VALID_MODES = ("module", "global")

_HEADER = (
    "// GENERATED by app_dsl/build.py -- do not edit by hand.\n"
    "// Regenerate from the DSL definition instead of editing this file.\n\n"
)


def _import_path(components_dir: str, out_dir: str, source: str) -> str:
    """A relative import path from the generated file's own directory
    (out_dir) to a component's source file (components_dir/source),
    with the .ts extension stripped (TypeScript's own import
    convention) and POSIX separators (import specifiers are URLs, not
    OS paths, even when generated on Windows). `mode="module"` only --
    `mode="global"` never imports anything."""
    absolute_source = os.path.normpath(os.path.join(components_dir, source))
    relative = os.path.relpath(absolute_source, out_dir)
    if os.sep != "/":
        relative = relative.replace(os.sep, "/")
    if relative.endswith(".ts"):
        relative = relative[: -len(".ts")]
    if not relative.startswith("."):
        relative = "./" + relative
    return relative


def _class_name_for_tag(tag: str) -> str:
    """"map-panel" -> "MapPanelElement" -- in `mode="module"`, this is
    just the generated import's own local alias, never required to
    match the component's real declared name. In `mode="global"`
    (no import to do any renaming), this is the *default* assumed
    real global class name -- see ComponentEntry.class_name for the
    override when a component's real name doesn't happen to match."""
    parts = [p for p in tag.replace("_", "-").split("-") if p]
    return "".join(p[:1].upper() + p[1:] for p in parts) + "Element"


def _resolved_class_name(component: ComponentEntry) -> str:
    return component.class_name or _class_name_for_tag(component.tag)


def _emit_registry(definition: AppDefinition, components_dir: str, out_dir: str, mode: str) -> list[str]:
    lines = []
    if mode == "module":
        for component in definition.components:
            class_name = _class_name_for_tag(component.tag)
            import_path = _import_path(components_dir, out_dir, component.source)
            lines.append(f'import {class_name} from "{import_path}";')
        lines.append("")
        for component in definition.components:
            class_name = _class_name_for_tag(component.tag)
            lines.append(f'customElements.define("{component.tag}", {class_name});')
        return lines
    # mode == "global": no imports -- each component's own file must
    # already declare a global class matching _resolved_class_name,
    # concatenated ahead of this file by the caller's own build
    # (tsconfig.json's "files" order, the same convention
    # build_widget.py's multi-file DefineWidget sources already use).
    for component in definition.components:
        lines.append(f'customElements.define("{component.tag}", {_resolved_class_name(component)});')
    return lines


def _emit_state(definition: AppDefinition, mode: str) -> list[str]:
    export_prefix = "export " if mode == "module" else ""
    lines = []
    for slot in definition.state:
        default_literal = _js_literal(slot.default)
        lines.append(f"{export_prefix}let {slot.name}: {slot.type} = {default_literal};")
        setter_name = "set" + slot.name[:1].upper() + slot.name[1:]
        lines.append(f"{export_prefix}function {setter_name}(value: {slot.type}): void {{")
        lines.append(f"  {slot.name} = value;")
        lines.append("}")
    return lines


def _js_literal(value: object) -> str:
    """A JSON default value, rendered as a JS/TS literal -- json.dumps
    already produces valid JS syntax for every value JSON itself can
    represent (null/true/false/numbers/strings/arrays/objects), so
    this is deliberately just that, not a second serializer."""
    return json.dumps(value)


def _emit_split_node_builder(node: SplitLayoutNode, fn_name: str, helpers: list[str], counter: list[int]) -> str:
    """Emits a builder function for one layout-tree node, returning
    its own function name; recurses for split children, allocating a
    fresh function name per node via `counter` (shared across the
    whole tree so names never collide). These helper functions are
    never exported in either mode -- only buildLayout (below) is a
    real entry point."""
    if node.type == "pane":
        helpers.append(f"function {fn_name}(): HTMLElement {{")
        helpers.append('  const el = document.createElement("div");')
        helpers.append('  el.className = "app-dsl-pane";')
        style_parts = []
        if node.min_size is not None:
            style_parts.append(f"min-width:{node.min_size}px;min-height:{node.min_size}px;")
        if node.max_size is not None:
            style_parts.append(f"max-width:{node.max_size}px;max-height:{node.max_size}px;")
        if style_parts:
            helpers.append(f'  el.style.cssText += "{"".join(style_parts)}";')
        helpers.append(f'  el.appendChild(document.createElement("{node.widget}"));')
        helpers.append("  return el;")
        helpers.append("}")
        return fn_name

    css_class = "app-dsl-hsplit" if node.type == "hsplit" else "app-dsl-vsplit"
    child_fn_names = []
    for child in node.children:
        counter[0] += 1
        child_fn_name = f"_buildNode{counter[0]}"
        child_fn_names.append(_emit_split_node_builder(child, child_fn_name, helpers, counter))

    helpers.append(f"function {fn_name}(): HTMLElement {{")
    helpers.append('  const el = document.createElement("div");')
    helpers.append(f'  el.className = "{css_class}";')
    for child_fn_name in child_fn_names:
        helpers.append(f"  el.appendChild({child_fn_name}());")
    helpers.append("  return el;")
    helpers.append("}")
    return fn_name


def _emit_layout(definition: AppDefinition, mode: str) -> list[str]:
    layout = definition.layout
    if layout is None:
        return []
    if layout.type == "windowed":
        raise DslError(
            "layout.type 'windowed' is not implemented by codegen yet "
            "(schema-only this pass -- see plans/app-structure-dsl.md's Key tradeoffs)"
        )
    if layout.type != "split":
        raise DslError(f"layout.type {layout.type!r} is not implemented by codegen")

    export_prefix = "export " if mode == "module" else ""
    lines: list[str] = []
    variant_builder_names = {}
    counter = [0]
    for variant_name, tree in layout.variants.items():
        counter[0] += 1
        root_fn_name = f"_buildVariant{counter[0]}"
        helpers: list[str] = []
        _emit_split_node_builder(tree, root_fn_name, helpers, counter)
        lines.extend(helpers)
        variant_builder_names[variant_name] = root_fn_name

    lines.append(f"{export_prefix}function buildLayout(variant: string): HTMLElement {{")
    for variant_name, fn_name in variant_builder_names.items():
        lines.append(f'  if (variant === "{variant_name}") {{ return {fn_name}(); }}')
    lines.append('  throw new Error("app_dsl: unknown layout variant: " + variant);')
    lines.append("}")
    lines.append(f'{export_prefix}const DEFAULT_LAYOUT_VARIANT = "{layout.default_variant}";')
    return lines


def _escape_target_identifier(action: CallAction, definition: AppDefinition, mode: str) -> str:
    """The escape:<key> naming in the DSL is always a *local* alias
    into AppDefinition.handlers -- in mode="module" the generated
    import is what actually binds that alias (`import { real_export as
    key } from ...`), so referring to `key` in the call site is
    correct. mode="global" has no import/alias step at all, so the
    call site must reference the handler's *real* global name
    (HandlerRef.export) directly instead."""
    handler_name = action.target[len("escape:") :]
    if mode == "module":
        return handler_name
    return definition.handlers[handler_name].export


def _emit_action(action, definition: AppDefinition, mode: str) -> str:
    if isinstance(action, StateMutationAction):
        setter_name = "set" + action.target[:1].upper() + action.target[1:]
        return f"  {setter_name}({action.source_expr});"
    if isinstance(action, CallAction):
        args = ", ".join(action.args)
        if action.target.startswith("escape:"):
            identifier = _escape_target_identifier(action, definition, mode)
            return f"  {identifier}({args});"
        return f'  (root.querySelector("{action.target}") as any)?.{action.method}({args});'
    raise DslError(f"unknown action type: {action!r}")  # pragma: no cover -- parser already rejects this


def _emit_event_wiring(definition: AppDefinition, mode: str) -> list[str]:
    export_prefix = "export " if mode == "module" else ""
    lines = [f"{export_prefix}function wireEvents(root: HTMLElement): void {{"]
    for entry in definition.events:
        lines.append(f'  root.querySelectorAll("{entry.emitter}").forEach((el) => {{')
        lines.append(f'    el.addEventListener("{entry.event}", (event: any) => {{')
        for action in entry.actions:
            lines.append("    " + _emit_action(action, definition, mode))
        lines.append("    });")
        lines.append("  });")
    lines.append("}")
    return lines


def _emit_handler_imports(definition: AppDefinition, components_dir: str, out_dir: str, mode: str) -> list[str]:
    if mode != "module":
        # mode="global": nothing to import -- each handler's own file
        # must already declare a global function named
        # HandlerRef.export, concatenated ahead of this file the same
        # way component files are (see _emit_registry).
        return []
    lines = []
    for name, handler in definition.handlers.items():
        import_path = _import_path(components_dir, out_dir, handler.module)
        lines.append(f'import {{ {handler.export} as {name} }} from "{import_path}";')
    return lines


def _emit_css(definition: AppDefinition) -> str | None:
    if definition.layout is None or definition.layout.type != "split":
        return None
    return (
        "/* GENERATED by app_dsl/build.py -- do not edit by hand. */\n\n"
        ".app-dsl-hsplit { display: flex; flex-direction: row; width: 100%; height: 100%; }\n"
        ".app-dsl-vsplit { display: flex; flex-direction: column; width: 100%; height: 100%; }\n"
        ".app-dsl-pane { flex: 1; overflow: auto; }\n"
    )


def generate(
    definition: AppDefinition, components_dir: str, out_dir: str, mode: str = "module"
) -> dict[str, str]:
    """Returns {filename: content} for every file this DSL definition
    generates -- always GENERATED_TS_FILENAME, plus
    GENERATED_CSS_FILENAME if the layout is a "split" layout. Raises
    DslError for anything this pass doesn't implement codegen for yet
    (see _emit_layout), or for an unknown `mode`, rather than silently
    emitting wrong output. See this module's own docstring for what
    `mode` controls."""
    if mode not in VALID_MODES:
        raise DslError(f"mode must be one of {VALID_MODES}, got {mode!r}")

    ts_lines = [_HEADER.rstrip("\n")]
    ts_lines.append("")
    ts_lines.extend(_emit_handler_imports(definition, components_dir, out_dir, mode))
    ts_lines.extend(_emit_registry(definition, components_dir, out_dir, mode))
    ts_lines.append("")
    ts_lines.extend(_emit_state(definition, mode))
    ts_lines.append("")
    ts_lines.extend(_emit_layout(definition, mode))
    ts_lines.append("")
    ts_lines.extend(_emit_event_wiring(definition, mode))
    ts_text = "\n".join(ts_lines) + "\n"

    outputs = {GENERATED_TS_FILENAME: ts_text}
    css_text = _emit_css(definition)
    if css_text is not None:
        outputs[GENERATED_CSS_FILENAME] = css_text
    return outputs
