"""Generates real TypeScript (+ CSS, for a "split" layout) from a
parsed AppDefinition (schema.py) -- see README.md for the DSL format
and plans/app-structure-dsl.md (Desk repo) for the design this
implements.

The generated code has zero Desk-specific content in it (no Bridge API
calls, nothing) unless an escape-hatch handler's own hand-written code
adds some -- "dual transpilation target" (standalone vs. a Desk
kind:"html" widget build) needs no separate codegen mode here: this is
the *only* codegen target, and whichever build pipeline picks up the
output afterward is what actually differs. See DslError for the
one class of thing this module refuses to generate."""

import os

from schema import (
    AppDefinition,
    CallAction,
    DslError,
    EventWiringEntry,
    SplitLayoutNode,
    StateMutationAction,
)

GENERATED_TS_FILENAME = "app-wiring.ts"
GENERATED_CSS_FILENAME = "app-layout.css"

_HEADER = (
    "// GENERATED by app_dsl/build.py -- do not edit by hand.\n"
    "// Regenerate from the DSL definition instead of editing this file.\n\n"
)


def _import_path(components_dir: str, out_dir: str, source: str) -> str:
    """A relative import path from the generated file's own directory
    (out_dir) to a component's source file (components_dir/source),
    with the .ts extension stripped (TypeScript's own import
    convention) and POSIX separators (import specifiers are URLs, not
    OS paths, even when generated on Windows)."""
    absolute_source = os.path.normpath(os.path.join(components_dir, source))
    relative = os.path.relpath(absolute_source, out_dir)
    if os.sep != "/":
        relative = relative.replace(os.sep, "/")
    if relative.endswith(".ts"):
        relative = relative[: -len(".ts")]
    if not relative.startswith("."):
        relative = "./" + relative
    return relative


def _class_name_for_tag(tag: str) -> str:
    """"map-panel" -> "MapPanelElement" -- the default-exported
    class's assumed name is never actually referenced by name (the
    import is a default import, aliased to this), so this only needs
    to be a valid, readable TS identifier, not match anything the
    component's own source file actually calls itself."""
    parts = [p for p in tag.replace("_", "-").split("-") if p]
    return "".join(p[:1].upper() + p[1:] for p in parts) + "Element"


def _emit_registry(definition: AppDefinition, components_dir: str, out_dir: str) -> list[str]:
    lines = []
    for component in definition.components:
        class_name = _class_name_for_tag(component.tag)
        import_path = _import_path(components_dir, out_dir, component.source)
        lines.append(f'import {class_name} from "{import_path}";')
    lines.append("")
    for component in definition.components:
        class_name = _class_name_for_tag(component.tag)
        lines.append(f'customElements.define("{component.tag}", {class_name});')
    return lines


def _emit_state(definition: AppDefinition) -> list[str]:
    lines = []
    for slot in definition.state:
        default_literal = _js_literal(slot.default)
        lines.append(f"export let {slot.name}: {slot.type} = {default_literal};")
        setter_name = "set" + slot.name[:1].upper() + slot.name[1:]
        lines.append(f"export function {setter_name}(value: {slot.type}): void {{")
        lines.append(f"  {slot.name} = value;")
        lines.append("}")
    return lines


def _js_literal(value: object) -> str:
    """A JSON default value, rendered as a JS/TS literal -- json.dumps
    already produces valid JS syntax for every value JSON itself can
    represent (null/true/false/numbers/strings/arrays/objects), so
    this is deliberately just that, not a second serializer."""
    import json

    return json.dumps(value)


def _emit_split_node_builder(node: SplitLayoutNode, fn_name: str, helpers: list[str], counter: list[int]) -> str:
    """Emits a builder function for one layout-tree node, returning
    its own function name; recurses for split children, allocating a
    fresh function name per node via `counter` (shared across the
    whole tree so names never collide)."""
    if node.type == "pane":
        helpers.append(f"function {fn_name}(): HTMLElement {{")
        helpers.append('  const el = document.createElement("div");')
        helpers.append('  el.className = "app-dsl-pane";')
        style_parts = []
        if node.min_size is not None:
            style_parts.append(f"min-width:{node.min_size}px;min-height:{node.min_size}px;")
        if node.max_size is not None:
            style_parts.append(f"max-width:{node.max_size}px;max-height:{node.max_size}px;")
        if style_parts:
            helpers.append(f'  el.style.cssText += "{"".join(style_parts)}";')
        helpers.append(f'  el.appendChild(document.createElement("{node.widget}"));')
        helpers.append("  return el;")
        helpers.append("}")
        return fn_name

    css_class = "app-dsl-hsplit" if node.type == "hsplit" else "app-dsl-vsplit"
    child_fn_names = []
    for child in node.children:
        counter[0] += 1
        child_fn_name = f"_buildNode{counter[0]}"
        child_fn_names.append(_emit_split_node_builder(child, child_fn_name, helpers, counter))

    helpers.append(f"function {fn_name}(): HTMLElement {{")
    helpers.append('  const el = document.createElement("div");')
    helpers.append(f'  el.className = "{css_class}";')
    for child_fn_name in child_fn_names:
        helpers.append(f"  el.appendChild({child_fn_name}());")
    helpers.append("  return el;")
    helpers.append("}")
    return fn_name


def _emit_layout(definition: AppDefinition) -> list[str]:
    layout = definition.layout
    if layout is None:
        return []
    if layout.type == "windowed":
        raise DslError(
            "layout.type 'windowed' is not implemented by codegen yet "
            "(schema-only this pass -- see plans/app-structure-dsl.md's Key tradeoffs)"
        )
    if layout.type != "split":
        raise DslError(f"layout.type {layout.type!r} is not implemented by codegen")

    lines: list[str] = []
    variant_builder_names = {}
    counter = [0]
    for variant_name, tree in layout.variants.items():
        counter[0] += 1
        root_fn_name = f"_buildVariant{counter[0]}"
        helpers: list[str] = []
        _emit_split_node_builder(tree, root_fn_name, helpers, counter)
        lines.extend(helpers)
        variant_builder_names[variant_name] = root_fn_name

    lines.append("export function buildLayout(variant: string): HTMLElement {")
    for variant_name, fn_name in variant_builder_names.items():
        lines.append(f'  if (variant === "{variant_name}") {{ return {fn_name}(); }}')
    lines.append('  throw new Error("app_dsl: unknown layout variant: " + variant);')
    lines.append("}")
    lines.append(f'export const DEFAULT_LAYOUT_VARIANT = "{layout.default_variant}";')
    return lines


def _emit_action(action) -> str:
    if isinstance(action, StateMutationAction):
        setter_name = "set" + action.target[:1].upper() + action.target[1:]
        return f"  {setter_name}({action.source_expr});"
    if isinstance(action, CallAction):
        args = ", ".join(action.args)
        if action.target.startswith("escape:"):
            handler_name = action.target[len("escape:") :]
            return f"  {handler_name}({args});"
        return f'  (root.querySelector("{action.target}") as any)?.{action.method}({args});'
    raise DslError(f"unknown action type: {action!r}")  # pragma: no cover -- parser already rejects this


def _emit_event_wiring(definition: AppDefinition) -> list[str]:
    lines = ["export function wireEvents(root: HTMLElement): void {"]
    for entry in definition.events:
        lines.append(f'  root.querySelectorAll("{entry.emitter}").forEach((el) => {{')
        lines.append(f'    el.addEventListener("{entry.event}", (event: any) => {{')
        for action in entry.actions:
            lines.append("    " + _emit_action(action))
        lines.append("    });")
        lines.append("  });")
    lines.append("}")
    return lines


def _emit_handler_imports(definition: AppDefinition, components_dir: str, out_dir: str) -> list[str]:
    lines = []
    for name, handler in definition.handlers.items():
        import_path = _import_path(components_dir, out_dir, handler.module)
        lines.append(f'import {{ {handler.export} as {name} }} from "{import_path}";')
    return lines


def _emit_css(definition: AppDefinition) -> str | None:
    if definition.layout is None or definition.layout.type != "split":
        return None
    return (
        "/* GENERATED by app_dsl/build.py -- do not edit by hand. */\n\n"
        ".app-dsl-hsplit { display: flex; flex-direction: row; width: 100%; height: 100%; }\n"
        ".app-dsl-vsplit { display: flex; flex-direction: column; width: 100%; height: 100%; }\n"
        ".app-dsl-pane { flex: 1; overflow: auto; }\n"
    )


def generate(definition: AppDefinition, components_dir: str, out_dir: str) -> dict[str, str]:
    """Returns {filename: content} for every file this DSL definition
    generates -- always GENERATED_TS_FILENAME, plus
    GENERATED_CSS_FILENAME if the layout is a "split" layout. Raises
    DslError for anything this pass doesn't implement codegen for yet
    (see _emit_layout) rather than silently emitting wrong output."""
    ts_lines = [_HEADER.rstrip("\n")]
    ts_lines.append("")
    ts_lines.extend(_emit_handler_imports(definition, components_dir, out_dir))
    ts_lines.extend(_emit_registry(definition, components_dir, out_dir))
    ts_lines.append("")
    ts_lines.extend(_emit_state(definition))
    ts_lines.append("")
    ts_lines.extend(_emit_layout(definition))
    ts_lines.append("")
    ts_lines.extend(_emit_event_wiring(definition))
    ts_text = "\n".join(ts_lines) + "\n"

    outputs = {GENERATED_TS_FILENAME: ts_text}
    css_text = _emit_css(definition)
    if css_text is not None:
        outputs[GENERATED_CSS_FILENAME] = css_text
    return outputs
