# TODO 94a2fa2: a fast, always-run verify script for the rust kind of
# Installed Jobs. Deliberately uses a Cargo project with NO external
# crate dependencies (no [dependencies] at all) -- compiles in well
# under a second, no crates.io fetch -- so this stays in the normal
# regression sweep. Real GPU-crate (wgpu) coverage, which is slow to
# build the first time, lives separately in
# disabled_verify_installed_jobs_rust_gpu.py.
import json
import os
import subprocess
import sys
import tempfile
import threading
import time
from pathlib import Path

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

import desk.shell.widget_frame  # noqa: E402  (imported before QApplication -- WebEngine ordering)
import desk.shell.canvas  # noqa: E402
from PyQt6.QtWebEngineWidgets import QWebEngineView  # noqa: E402,F401

from PyQt6.QtWidgets import QApplication  # noqa: E402

app = QApplication.instance() or QApplication(sys.argv)

from desk.desks import Desk, StateEntry  # noqa: E402
from desk.installed_jobs import (  # noqa: E402
    INSTALLED_JOBS_DIRNAME,
    InstalledJobDefinition,
    compute_version_hash,
    detect_kind,
    installed_job_dir,
)
from desk.shell.window import DeskWindow  # noqa: E402
from desk.temp_ui import (  # noqa: E402
    GITIGNORE_COMMENT,
    INSTALLED_JOBS_RUST_TARGET_GITIGNORE_ENTRY,
    ensure_installed_jobs_gitignore_entry,
)

passed = 0
failed = 0


def check(name, condition):
    global passed, failed
    if condition:
        passed += 1
        print(f"PASS: {name}")
    else:
        failed += 1
        print(f"FAIL: {name}")


def _git_init(directory):
    subprocess.run(["git", "init", "-q"], cwd=directory, check=True)


# A minimal, dependency-free Cargo project -- see this file's own
# header comment for why no [dependencies].
_CARGO_TOML = """[package]
name = "greet_rust"
version = "0.1.0"
edition = "2021"
"""
_MAIN_RS = """use std::env;
use std::fs;

fn main() {
    let config = env::var("DESK_JOB_CONFIG_PATH").ok();
    println!("CONFIG={:?}", config);
    match env::var("DESK_JOB_NEEDS_PATH") {
        Ok(needs_path) => {
            let content = fs::read_to_string(&needs_path).unwrap_or_default();
            println!("NEEDS={}", content);
        }
        Err(_) => println!("NEEDS=None"),
    }
    println!("hello from rust");
}
"""


def _write_rust_job(job_dir: Path, main_rs: str = _MAIN_RS) -> None:
    (job_dir / "src").mkdir(parents=True, exist_ok=True)
    (job_dir / "Cargo.toml").write_text(_CARGO_TOML)
    (job_dir / "src" / "main.rs").write_text(main_rs)


check(
    "INSTALLED_JOBS_RUST_TARGET_GITIGNORE_ENTRY is desk-installed-jobs/**/target/",
    INSTALLED_JOBS_RUST_TARGET_GITIGNORE_ENTRY == f"{INSTALLED_JOBS_DIRNAME}/**/target/",
)


def test_detect_kind():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as d:
        job_dir = Path(d) / "job"
        job_dir.mkdir()
        check("neither file present: None", detect_kind(job_dir) is None)
        (job_dir / "main.py").write_text("print('hi')\n")
        check("only main.py: python", detect_kind(job_dir) == "python")
        (job_dir / "Cargo.toml").write_text(_CARGO_TOML)
        check("both present: ambiguous, None", detect_kind(job_dir) is None)
        (job_dir / "main.py").unlink()
        check("only Cargo.toml: rust", detect_kind(job_dir) == "rust")


def test_compute_version_hash_excludes_target():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as d:
        job_dir = Path(d) / "job"
        _write_rust_job(job_dir)
        before = compute_version_hash(job_dir)
        (job_dir / "target" / "release").mkdir(parents=True)
        (job_dir / "target" / "release" / "greet_rust").write_bytes(b"fake binary bytes")
        (job_dir / "target" / "release" / "extra.d").write_text("build metadata\n")
        after = compute_version_hash(job_dir)
        check("hash unaffected by files under target/", before == after)


def test_compute_version_hash_excludes_root_cargo_lock():
    """TODO 94a2fa2: a real bug found via this item's own verification
    -- `cargo build` writes/updates Cargo.lock at the project root (not
    under target/) the first time it runs without one, which would
    otherwise make a job's very first real build look like a source
    change too, exactly like the target/ case above."""
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as d:
        job_dir = Path(d) / "job"
        _write_rust_job(job_dir)
        before = compute_version_hash(job_dir)
        (job_dir / "Cargo.lock").write_text('# auto-generated by cargo build\nversion = 3\n')
        after = compute_version_hash(job_dir)
        check("hash unaffected by a root-level Cargo.lock appearing", before == after)
        # A nested file that merely happens to be *named* Cargo.lock
        # (not the real root lockfile) is not exempted -- the exclusion
        # is deliberately narrow (see compute_version_hash's own
        # docstring), not "ignore every file named Cargo.lock anywhere".
        (job_dir / "src" / "Cargo.lock").write_text("not the real one\n")
        nested = compute_version_hash(job_dir)
        check("a nested src/Cargo.lock (not the real root one) still affects the hash", nested != after)


# ---------- ensure_installed_jobs_gitignore_entry (mirrors
# ensure_desk_widgets_gitignore_entry's own verify shape) ----------


def test_gitignore_noop_when_no_installed_jobs_dir():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as d:
        directory = Path(d)
        _git_init(directory)
        calls = []
        ensure_installed_jobs_gitignore_entry(directory, ask=lambda: calls.append(1) or True)
        check("no desk-installed-jobs/ at all: ask() never called", calls == [])
        check("no desk-installed-jobs/ at all: no .gitignore created", not (directory / ".gitignore").exists())


def test_gitignore_fresh():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as d:
        directory = Path(d)
        _git_init(directory)
        (directory / INSTALLED_JOBS_DIRNAME).mkdir()
        ensure_installed_jobs_gitignore_entry(directory, ask=lambda: True)
        text = (directory / ".gitignore").read_text()
        check(
            "fresh .gitignore gets blank line + comment + the entry",
            text == f"\n{GITIGNORE_COMMENT}\n{INSTALLED_JOBS_RUST_TARGET_GITIGNORE_ENTRY}\n",
        )


def test_gitignore_already_present_is_noop():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as d:
        directory = Path(d)
        _git_init(directory)
        (directory / INSTALLED_JOBS_DIRNAME).mkdir()
        existing = f"{INSTALLED_JOBS_RUST_TARGET_GITIGNORE_ENTRY}\n"
        (directory / ".gitignore").write_text(existing)
        calls = []
        ensure_installed_jobs_gitignore_entry(directory, ask=lambda: calls.append(1) or True)
        check("entry already present: ask() never called", calls == [])
        check("entry already present: .gitignore untouched", (directory / ".gitignore").read_text() == existing)


# ---------- install_job / run_installed_job (real DeskWindow logic,
# same _FakeWindowForRun technique verify_installed_jobs.py uses)
# ----------


class _FakeWindowForRun:
    def __init__(self, directory: Path, installed_jobs: list) -> None:
        self.current_desk = Desk(path=directory / "default.desk", installed_jobs=installed_jobs)
        self._schema_registry = type("S", (), {"get": lambda self, k: None})()
        self.confirmed_titles = []

    def _confirm_fn(self, title, message):
        self.confirmed_titles.append(title)
        return lambda: True

    def _event_mediator_publish_noop(self, *a, **k):
        pass

    get_installed_job = DeskWindow.get_installed_job
    get_installed_job_for_run = DeskWindow.get_installed_job_for_run
    run_installed_job = DeskWindow.run_installed_job
    install_job = DeskWindow.install_job
    get_installed_jobs_dicts = DeskWindow.get_installed_jobs_dicts
    get_state = DeskWindow.get_state
    _resolve_job_needs = DeskWindow._resolve_job_needs
    # TODO 0959ff1: see verify_installed_jobs.py's own identical
    # comment on these two.
    _prepare_installed_job_run = DeskWindow._prepare_installed_job_run
    _make_run_installed_job_callable = DeskWindow._make_run_installed_job_callable

    def save_current_desk(self) -> None:
        pass

    @property
    def _event_mediator(self):
        return type("M", (), {"publish": lambda self, *a, **k: None})()


def _wait(predicate, timeout=30.0):
    deadline = time.time() + timeout
    while time.time() < deadline:
        if predicate():
            return True
        time.sleep(0.02)
    return False


def test_install_job_detects_rust_kind():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as d:
        directory = Path(d)
        job_dir = installed_job_dir(directory, "greet")
        _write_rust_job(job_dir)
        window = _FakeWindowForRun(directory, [])
        ok, message = window.install_job("greet")
        check("install_job succeeds for a rust-kind job", ok)
        check("install_job's message names the kind", "kind rust" in message)
        check("registry now has one entry", len(window.current_desk.installed_jobs) == 1)
        dicts = window.get_installed_jobs_dicts()
        check("get_installed_jobs_dicts reports kind=rust", dicts[0]["kind"] == "rust")


def test_install_job_rejects_ambiguous_or_missing_kind():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as d:
        directory = Path(d)
        window = _FakeWindowForRun(directory, [])
        ok, message = window.install_job("nothing-here")
        check("install_job refuses when neither entry file exists", not ok)

        job_dir = installed_job_dir(directory, "both")
        _write_rust_job(job_dir)
        (job_dir / "main.py").write_text("print('hi')\n")
        ok, message = window.install_job("both")
        check("install_job refuses when both entry files exist (ambiguous)", not ok)


def test_run_rust_job_builds_and_executes():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as d:
        directory = Path(d)
        job_dir = installed_job_dir(directory, "greet")
        _write_rust_job(job_dir)
        real_hash = compute_version_hash(job_dir)
        window = _FakeWindowForRun(
            directory,
            [InstalledJobDefinition(name="greet", version_hash=real_hash, installed_at="2026-01-01T00:00:00")],
        )

        results = []
        window.run_installed_job("greet", None, lambda ok, out, err, tb: results.append((ok, out, err, tb)))
        ok = _wait(lambda: results, timeout=120.0)
        check("run_installed_job eventually reports a result (build + run)", ok)
        if results:
            run_ok, stdout, stderr, tb = results[0]
            check("the rust binary ran successfully", run_ok, )
            check("stdout captured the job's own output", "hello from rust" in stdout)
            check("CONFIG_PATH env var was unset (None) when no config_path given", "CONFIG=None" in stdout)
            check("no traceback on success", tb == "")
        binary = job_dir / "target" / "release" / "greet_rust"
        check("a real compiled binary now exists under target/release/", binary.is_file())

        # Second run: the binary should not need rebuilding (mtime
        # unchanged) and should still execute correctly.
        first_mtime = binary.stat().st_mtime
        results2 = []
        window.run_installed_job("greet", None, lambda ok, out, err, tb: results2.append((ok, out, err, tb)))
        _wait(lambda: results2, timeout=30.0)
        check("second run does not rebuild the binary", binary.stat().st_mtime == first_mtime)
        check("second run still succeeds", results2 and results2[0][0])


def test_run_rust_job_config_and_needs_env_vars():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as d:
        directory = Path(d)
        job_dir = installed_job_dir(directory, "greet")
        _write_rust_job(job_dir)
        (job_dir / "job.json").write_text(json.dumps({"needs": ["some_key"]}))
        real_hash = compute_version_hash(job_dir)
        window = _FakeWindowForRun(
            directory,
            [InstalledJobDefinition(name="greet", version_hash=real_hash, installed_at="2026-01-01T00:00:00")],
        )
        window.current_desk.state["some_key"] = StateEntry(value=42, edit="set by test")

        cfg = directory / "cfg.json"
        cfg.write_text("{}")
        results = []
        window.run_installed_job(
            "greet", str(cfg), lambda ok, out, err, tb: results.append((ok, out, err, tb))
        )
        ok = _wait(lambda: results, timeout=120.0)
        check("run with config_path + needs eventually reports a result", ok)
        if results:
            run_ok, stdout, stderr, tb = results[0]
            check("run succeeded", run_ok)
            check("DESK_JOB_CONFIG_PATH reached the job", f'CONFIG=Some("{cfg}")' in stdout)
            check("DESK_JOB_NEEDS_PATH reached the job with the resolved value", '"some_key"' in stdout and "42" in stdout)
        needs_file = directory / ".desk_temp" / "installed-job-needs" / "greet.json"
        check("the needs file itself matches what get_state returns", json.loads(needs_file.read_text()) == {"some_key": {"value": 42, "edit": "set by test"}})


def test_stale_source_refuses_run_and_reinstall_clears_it():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as d:
        directory = Path(d)
        job_dir = installed_job_dir(directory, "greet")
        _write_rust_job(job_dir)
        real_hash = compute_version_hash(job_dir)
        window = _FakeWindowForRun(
            directory,
            [InstalledJobDefinition(name="greet", version_hash=real_hash, installed_at="2026-01-01T00:00:00")],
        )
        (job_dir / "src" / "main.rs").write_text(_MAIN_RS.replace("hello from rust", "hello v2"))
        try:
            window.run_installed_job("greet", None, lambda *a: None)
            check("stale source raises ValueError before anything runs", False)
        except ValueError as e:
            check("stale source raises ValueError before anything runs", "no longer matches" in str(e))
        ok, _message = window.install_job("greet")
        check("re-installing succeeds", ok)
        results = []
        window.run_installed_job("greet", None, lambda ok, out, err, tb: results.append((ok, out, err, tb)))
        _wait(lambda: results, timeout=120.0)
        check("after re-install, run succeeds with the new source", results and results[0][0] and "hello v2" in results[0][1])


test_detect_kind()
test_compute_version_hash_excludes_target()
test_compute_version_hash_excludes_root_cargo_lock()
test_gitignore_noop_when_no_installed_jobs_dir()
test_gitignore_fresh()
test_gitignore_already_present_is_noop()
test_install_job_detects_rust_kind()
test_install_job_rejects_ambiguous_or_missing_kind()
test_run_rust_job_builds_and_executes()
test_run_rust_job_config_and_needs_env_vars()
test_stale_source_refuses_run_and_reinstall_clears_it()

print(f"\n{passed} passed, {failed} failed")
sys.exit(1 if failed else 0)
